### ISSUE TITLE
Опечатка в ReadMe.md 

### ISSUE THREAD

**Issue by phant** [Krot66/LangBarXX#1]
Предпоследний вопрос _В. Как быстро заменить на LangBar++ имеющийся индикатор раскладки..._ при **нобходимости** сохранения настроек...

**нобходимости** -> **необходимости**

**Comment by phant** [comment]
Другие опечатки и ошибки в ReadMe.html / ReadMe.md

1. ометьте
2. рабоатет
3. появитя
4. посисмволное
5. посимволного
6. кусора
7. чередоаться
8. связано с масштабировании интерфейса -> с масштабированием
9. В отличии от -> В отличи**е** от
10. расмотренных  -> ра**сс**мотренных  
11. где то -> где-то

**Comment by DimNS** [comment]
Ну это можно было форкнуть репозиторий и пулл-реквест сделать )

**Comment by Krot66** [comment]
Ни одной ошибки из приведенных в оригинальном md-файле не нашел. Откуда это может взяться?
