### ISSUE TITLE
Дополнительные клавиши для исправления раскладки

### ISSUE THREAD

**Issue by DimNS** [Krot66/LangBarXX#10]
У меня на клавиатуре нет паузы, а Ctrl+CapsLock и Shift+Baskspace это две клавиши зажимать надо.

Предлагаю сделать возможность выбрать одну клавишу: левый\правый Shift или левый\правый Ctrl и нажимать их дважды

Так сделано в Caramba Switcher (который наследник Punto Switcher)

Довольно удобно, выделил кусок текста и дважды на Shift

**Comment by DimNS** [comment]
Немного не понял вашу мысль, почему не подходит двойное нажатие на шифт при выделенном тексте?

**Comment by Krot66** [comment]
Пока клавиши зажаты, происходит последовательное выделение слов. Можно быстро отпустить и снова нажать клавишу - тогда будут выделяться знаки. Собственно, в начале это была программа для чисто ручного исправления раскладки. Уже потом было решено делать автоматику.

**Comment by DimNS** [comment]
Дак мне и нужно ручное исправление раскладки, попробую еще раз описать кейс
1. я написал текст в неправильной раскладке
2. сам выделил кусок текста (теперь текст в выделенном состоянии)
3. быстро нажал дважды левый Shift
4. программа взяла выделенный кусок текста и сменила раскладку
При этом в настройках весь раздел "Переключение раскладки" выключен и все галочки сняты

**Comment by Krot66** [comment]
То, о чем вы говорите, есть только вопрос привычки. Нет реального смысла что-то менять только для обработки выделенного текста, что должно вообще составлять малую часть всех преобразований, автоматических и ручных.

**Comment by xperiandri** [comment]
Я вот не понял ни их руководства ни из описания как всё таки вручную раскладку переключить.
Есть ли где-то пошаговая инструкция?

**Comment by DimNS** [comment]
@xperiandri вы написали текст в неверной раскладке, увидели это, выделили кусок текста и нажали Shift+Baskspace, текст сменил раскладку

Если вы про это

**Comment by DimNS** [comment]
@Krot66 вы правы, со временем я привык к Shift+Baskspace )) и теперь делаю это на автомате
