### ISSUE TITLE
Лаги в интерфейсе системы и приложениях

### ISSUE THREAD

**Issue by Dreamer-4pda** [Krot66/LangBarXX#15]
При запущенном приложении LangBar происходит задержка курсора и его реакции на нажатие.
Хорошо заметно в меню "Пуск" и панели виджетов. Также в фотошоп и иллюстратор это проявляется при выполнении операций с зажатой клавишей ctrl. В игре Project Zomboid проявляется в виде не всегда срабатывающего щелчка правой кнопкой мыши.

**Comment by Krot66** [comment]
Мне писали об этом - попробуйте версию 1.7.2

**Comment by Dreamer-4pda** [comment]
Установил версию 1.7.2
Теперь все ОК
