### ISSUE TITLE
Удаляются символы справа от каретки

### ISSUE THREAD

**Issue by Lichtenshtein** [Krot66/LangBarXX#2]
LangBarXX "съедает" 1 любой символ справа от каретки, при исправлении раскладки текста (по shift+bs). Буквы, пустые строки, пробелы.

**Comment by Krot66** [comment]
Увидел, хотя сходу и не понять, как такое происходит. Будем думать

**Comment by Lichtenshtein** [comment]
В версии 1.2 проблема пропала.
