### ISSUE TITLE
Программы исключения для автопереключения

### ISSUE THREAD

**Issue by Dreamer-4pda** [Krot66/LangBarXX#9]
Есть ли способ добавить программу в исключения для автопереключения?
Работаю в основном при помощи хоткеев и при включенном автопереключении постоянно меняется раскладка.

**Comment by Krot66** [comment]
Есть автопереключение - пользовательский словарь. Ввести начальную неизменную часть слова на любом языке

**Comment by Dreamer-4pda** [comment]
Не совсем понял, как это скажет программе не переключать раскладку в Фотошопе, например.
Вот я рисую и постоянно использую кнопки b, e, x в разной последовательности. Программа переключает раскладку туда-сюда, думая что я печатаю...
В пунто я просто добавлял Фотошоп в исключения и автопереключение там не работало.

**Comment by Krot66** [comment]
Сделано в версии 1.5.0 (диалог правила приложений)
